source "http://rubygems.org"

# Declare your gem's dependencies in catch.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem 'jquery-rails'

 # rails plugin new catch --mountable
 # rails g controller failures index
 # rails g model failure message:text
 # rake catch:install:migrations # { in main engine, if rake db:migrate fails }